### ISSUE TITLE
Crash when running example

### ISSUE THREAD

**Issue by git-commit** [hpreston/webexteamsbot#1]
* webexteamsbot version: 0.1.2.1
* Python version: 3.7
* Operating System: Windows

### Description

1. Make a new Virtualenv
2. Install the library
3. Try to run the example

### What I Did
Running the provided sample results in the following stacktrace:
```
Traceback (most recent call last):
  File "bot.py", line 15, in <module>
    teams_bot_email=bot_email,
  File "C:\Users\Max\Envs\wacker\lib\site-packages\webexteamsbot\webexteamsbot.py", line 43, in __init__
    super(TeamsBot, self).__init__(teams_bot_name)
  File "C:\Users\Max\Envs\wacker\lib\site-packages\flask\app.py", line 371, in __init__
    root_path=root_path
  File "C:\Users\Max\Envs\wacker\lib\site-packages\flask\helpers.py", line 891, in __init__
    root_path = get_root_path(self.import_name)
  File "C:\Users\Max\Envs\wacker\lib\site-packages\flask\helpers.py", line 735, in get_root_path
    loader = pkgutil.get_loader(import_name)
  File "c:\python37\Lib\pkgutil.py", line 479, in get_loader
    return find_loader(fullname)
  File "c:\python37\Lib\pkgutil.py", line 489, in find_loader
    if fullname.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by DockCZ** [comment]
Hi have entered environment variables?

export TEAMS_BOT_URL=https://mypublicsite.io
export TEAMS_BOT_TOKEN=<your bots token>
export TEAMS_BOT_EMAIL=<your bots email>
export TEAMS_BOT_APP_NAME=<your bots name>

or for me also works editing the code:
`# Create a Bot Object
bot = TeamsBot(
    "<your bots name>",
    teams_bot_token=<your bots token>,
    teams_bot_url="https://mypublicsite.io",
    teams_bot_email=<your bots email>,
)`
